// Copyright Hkt Studios, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Containers/Array.h"
#include "HktEntityTypes.h"

namespace Hkt
{
    // ==================================================================================
    // Event Types (이벤트 태그 및 통합 이벤트)
    // ==================================================================================

    /** 이벤트 태그 정의 */
    enum class EEventTag : uint32
    {
        None = 0,
        Move = 1,           // Input Intent
        Skill = 2,          // Input Intent
        CollisionHit = 100, // System Event (Generated by Physics)
    };

    /**
     * 통합 이벤트 구조체 (Unified Event)
     * - 외부 입력(Intent)과 내부 시스템 발생(System) 이벤트를 통합 관리
     * - 직렬화 및 네트워크 전송 최적화는 bIsInternal 플래그 등을 활용해 처리 가능
     */
    struct FHktEvent
    {
        uint32 EventTag;       // EEventTag
        FEntityID Source;
        FEntityID Target;
        FVector3 Location;
        TArray<uint8> Payload; // Parameters

        /** 이 이벤트가 시스템 내부 발생인지 여부 (True면 네트워크 전송 제외 가능) */
        bool bIsInternal = false;
    };
}
