#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace HktGameplayTags
{
    // --- Story IDs used by Runtime ---
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Story_Event_Move_ToLocation);
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Story_PlayerInWorld);

    // --- Database Defaults ---
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Visual_Character_Default);
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flow_Character_Default);

    // --- Entity Classification ---
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Entity_Character);
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Entity_NPC);
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Entity_Building);
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Entity_Projectile);
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Entity_Item);

    // --- Animation Parent Tags ---
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim);
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_FullBody);
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage);
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_UpperBody);

    // --- Skill Slot Availability (엔티티에 태그가 있으면 해당 슬롯 비활성화) ---
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Slot_Disabled);     // Skill.Slot.Disabled (부모)
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Slot_Disabled_0);
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Slot_Disabled_1);
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Slot_Disabled_2);
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Slot_Disabled_3);
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Slot_Disabled_4);
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Slot_Disabled_5);
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Slot_Disabled_6);
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Slot_Disabled_7);
    HKTRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Slot_Disabled_8);
}
